"""add constaints

Revision ID: 0ad7ca9f345c
Revises: 308f9c0a4310
Create Date: 2023-02-19 18:37:29.189378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad7ca9f345c'
down_revision = '308f9c0a4310'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_article_name', table_name='article')
    op.create_index(op.f('ix_article_name'), 'article', ['name'], unique=True)
    op.create_index(op.f('ix_article_code'), 'article', ['code'], unique=True)
    op.drop_index('ix_tag_name', table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_index(op.f('ix_tag_code'), 'tag', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_code'), table_name='tag')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    op.drop_index(op.f('ix_article_code'), table_name='article')
    op.drop_index(op.f('ix_article_name'), table_name='article')
    op.create_index('ix_article_name', 'article', ['name'], unique=False)
    # ### end Alembic commands ###
