"""add relationship

Revision ID: 308f9c0a4310
Revises: 1901b18fb8cf
Create Date: 2023-02-19 17:45:03.453547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308f9c0a4310'
down_revision = '1901b18fb8cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_tags_id'), 'article_tags', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_tags_id'), table_name='article_tags')
    op.drop_table('article_tags')
    # ### end Alembic commands ###
